[build]
  environment = { NODE_VERSION = "20" }
  command = "pnpm run build"
  publish = "build"

[functions]
  node_bundler = "esbuild"

[functions."*"]
  format = "esm"

[functions."update-item-prices"]
  schedule = "@hourly"
